In [4]:
pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.67)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.7.1)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.19.5)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.23.0)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.1.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20->yfinance) (3.0.4)

In [5]:
import yfinance as yf
import pandas as pd
import numpy as np

BTC = yf.download(tickers='BTC-USD', period = '777d', interval = '1d')

[*********************100%***********************]  1 of 1 completed

In [6]:
reddit_data = pd.read_csv("group.csv")                                                      ### Reddit Data from the Reddit Post Generator Script
reddit_data['Date']= pd.to_datetime(reddit_data['Date'])
reddit_data = reddit_data.drop(columns=['Unnamed: 0'])
reddit_data = reddit_data.rename(columns={"0":"Average_Reddit_Sentiment"})

twitter_data = pd.read_csv("group2.csv")                                                     ### Twiiter Data from the Twitter Post Generator Script
twitter_data = pd.read_csv("group2.csv")
twitter_data['Date']= pd.to_datetime(twitter_data['Date'])
twitter_data = twitter_data.drop(columns=['Unnamed: 0'])
twitter_data = twitter_data.rename(columns={"sentiment_value":"Average_Twitter_Sentiment"})

data = BTC.copy()
data = data.reset_index()
data.drop(data.tail(16).index,inplace = True)

data = pd.merge(data, reddit_data, how="left", on=["Date"])
data = data.fillna(method="ffill")

data = pd.merge(data, twitter_data, how="left", on=["Date"])
data = data.fillna(method="ffill")

In [7]:
data

          Date  ...  Average_Twitter_Sentiment
0   2019-11-08  ...                   0.205640
1   2019-11-09  ...                   0.127930
2   2019-11-10  ...                   0.109529
3   2019-11-11  ...                   0.135262
4   2019-11-12  ...                   0.151131
..         ...  ...                        ...
756 2021-12-03  ...                   0.029366
757 2021-12-04  ...                   0.071585
758 2021-12-05  ...                   0.080183
759 2021-12-06  ...                  -0.014483
760 2021-12-07  ...                  -0.057336

[761 rows x 9 columns]

In [8]:
data['Open'].corr(data['Average_Reddit_Sentiment'])

0.08214679300668892

In [9]:
data['Open'].corr(data['Average_Twitter_Sentiment'])

0.012728526756371324

In [10]:
data.corr()

                               Open  ...  Average_Twitter_Sentiment
Open                       1.000000  ...                   0.012729
High                       0.999102  ...                   0.012643
Low                        0.998197  ...                   0.018908
Close                      0.997719  ...                   0.018897
Adj Close                  0.997719  ...                   0.018897
Volume                     0.401371  ...                  -0.061591
Average_Reddit_Sentiment   0.082147  ...                   0.026285
Average_Twitter_Sentiment  0.012729  ...                   1.000000

[8 rows x 8 columns]

In [11]:
import pandas as pd
from scipy.stats import pearsonr

pearsonr(data['Open'], data['Average_Reddit_Sentiment'])

(0.08214679300668883, 0.02343753367641892)